FROM node:hydrogen-alpine3.17

WORKDIR /usr/src/myapp

RUN npm install

# Exponha a porta 3000, se necessário
EXPOSE 3000

# Comando para iniciar seu aplicativo (ajuste conforme necessário)
CMD ["npm", "run", "dev"]
